[package]
name = "gpu_controller"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytemuck = "1.23.2"
log = "0.4.27"
wgpu = "25.0.2"
winit = "0.30.12"

[dev-dependencies]
smol = "2.0.2"
