[package]
name = "photon"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.1"
log = "0.4.27"
wgpu = "25.0.2"
gpu_controller = { path = "../gpu_controller" }
matter_vault = { path = "../matter_vault" }
anyhow = "1.0.98"
obj-loader = { path = "../../obj-loader" }
cgmath = "0.18.0"
