[package]
name = "isotope_test"
version = "0.1.0"
edition = "2024"

[features]
deadlock_detection = []

[dependencies]
isotope = { path = "../isotope" }
log = "0.4.28"
parking_lot = { version = "0.12.5", features = ["deadlock_detection"] }
pretty_env_logger = "0.5.0"
winit = "0.30.12"
